services:
  - type: web
    name: hdbadminton-bot
    env: python
    region: singapore
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RENDER
        value: "true"
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHONPATH
        value: "/opt/render/project/src"
    healthCheckPath: /health
